Add "trackAllPages" and "excludeUris" settings. The first allows acti…
tattersoftware/codeigniter4-visits pull request #15
Opened 2022-07-03 02:52 UTC by kgrruz

…vating or not the automatic tracking through the 'post_controller_constructor' event and the second excluding certain uri's from tracking.

2022-07-03 10:47 UTC, MGatner commented
I'm thrilled to have a PR here, thanks for contributing! Just a heads up that in the next major version this library will be refactored into a Filter, which will allow developers to apply/exclude it to specific routes. 
If you would still like to proceed with your feature submission please run CS Fixer (`composer style`) to enforce the style guide. Normally I'd want tests but this library is very old and I never wrote tests for it so I won't enforce that.

2022-07-03 10:54 UTC, MGatner requested changes

2022-07-03 10:54 UTC, MGatner commented on src/Config/Events.php
> +	$config = config('Tatter\Visits\Config\Visits');
Shorthand Config names are preferable:
```suggestion
	$config = config('Visits');
```

2022-07-03 10:54 UTC, MGatner commented on src/Config/Visits.php
> +	public $trackAllPages = false;
This needs to be `true` by default or current implementations will stop tracking when they upgrade. 
```suggestion
	public $trackAllPages = true;
```

2022-07-03 10:54 UTC, MGatner commented on src/Visits.php
> +				if (preg_match('#^'.$excluded.'$#iu', $visit->path))
Better to use CodeIgniter's helper function:
```suggestion
				if (url_is($excluded))
```

https://codeigniter4.github.io/CodeIgniter4/helpers/url_helper.html#url_is

2022-07-04 10:48 UTC, MGatner commented
@kgrruz I'm sorry, I shouldn't have told you to run CS Fixer as part of this PR - I didn't realize this repo hadn't been updated to use the CodeIgniter Style Guide. I will resolve the style and actions in the other PR and then see about cherry-picking your changes. Hold tight.

2022-07-04 11:50 UTC, kgrruz commented
OK. Thanks for the suggestions.

2022-07-04 18:56 UTC, closed without merging